### ISSUE TITLE
Add poetry support

### ISSUE THREAD

**Issue by PNoryk** [Whinarn/vscode-python-auto-venv#7]
I believe poetry is nowadays python dependency resolution practice. 
It would be great to add poetry support.

**Comment by Whinarn** [comment]
I've been working on supporting Poetry now, but have not yet properly tested everything yet.
Feel free to look over the [pull request](https://github.com/Whinarn/vscode-python-auto-venv/pull/8), or try it out if you have the time.

I haven't used Poetry myself yet, and have only written this based on the documentation available, so I'll give it some more test runs before I push out a new version with this.

**Comment by PNoryk** [comment]
I'm working on the pull request. But it's my first acquaintance with vscode and its extensions (especially debuting extensions)

UPD: I've done [pull request](https://github.com/Whinarn/vscode-python-auto-venv/pull/10)
